version: "3.9"
services:
  cart_service:
    build: ./services/cart_service
    container_name: cart_service
    ports:
      - "5001:5001"

  product_service:
    build: ./services/product_service
    container_name: product_service
    ports:
      - "5002:5002"
