#version: "3.9"
services:
  web:
#    image:
    build: .
    ports:
      - "8007:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: True
    deploy:
      replicas: 1
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
    volumes: ['./myredis/conf:/data ']
volumes:
  db_data:
